### ISSUE TITLE
Contradictory chat responses on song request

### ISSUE THREAD

**Issue by gCoreByte** [KumoKairo/Spotify-Twitch-Song-Requests#12]
https://prnt.sc/YFv9Cm3_q2CQ
Song is added to queue successfully, but it is still searched for, which fails.

**Comment by KumoKairo** [comment]
I should probably re-enable my affiliate because I cannot test channel points / bits right now. It works okay with command mode, so the issue is somewhere in the redemption code after the latest changes in 0.6.0. I will take a look and let someone test it if it's possible

**Comment by KumoKairo** [comment]
I have not been able to reproduce on 0.8.1
<img width="652" alt="image" src="https://user-images.githubusercontent.com/2943071/167440047-35096ba8-3f85-40ef-aada-4028cce4adac.png">

**Comment by gCoreByte** [comment]
Appears fixed on newer versions.
