### ISSUE TITLE
added_to_queue does not properly show username

### ISSUE THREAD

**Issue by ghlegend195** [KumoKairo/Spotify-Twitch-Song-Requests#4]
added_to_queue message shows $(username) instead of username requesting. 

Note: modified the added_to_queue to show "$(username) has added \"$(artists) - $(trackName)\" to the queue." Song info populates, but issue above occurs. Attn line 234?

**Comment by KumoKairo** [comment]
Noted.
Right now only `artist` and `trackName` are supported, I will add `username` too.
